rm -f libmath/copysignf.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libmath copysignf.lo
rm -f libmath/libmath.la; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libmath libmath.la
rm -f libmath/signbit.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libmath signbit.lo
rm -f libmath/signbitf.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libmath signbitf.lo
rm -f libmath/stubs.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libmath stubs.lo
rm -f libsupc++/cp-demangle.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ cp-demangle.lo
rm -f libsupc++/del_op.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ del_op.lo
rm -f libsupc++/del_opnt.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ del_opnt.lo
rm -f libsupc++/del_opv.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ del_opv.lo
rm -f libsupc++/del_opvnt.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ del_opvnt.lo
rm -f libsupc++/eh_alloc.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_alloc.lo
rm -f libsupc++/eh_aux_runtime.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_aux_runtime.lo
rm -f libsupc++/eh_catch.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_catch.lo
rm -f libsupc++/eh_exception.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_exception.lo
rm -f libsupc++/eh_globals.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_globals.lo
rm -f libsupc++/eh_personality.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_personality.lo
rm -f libsupc++/eh_term_handler.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_term_handler.lo
rm -f libsupc++/eh_terminate.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_terminate.lo
rm -f libsupc++/eh_throw.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_throw.lo
rm -f libsupc++/eh_type.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_type.lo
rm -f libsupc++/eh_unex_handler.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ eh_unex_handler.lo
rm -f libsupc++/guard.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ guard.lo
rm -f libsupc++/libsupc++.la; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ libsupc++.la
rm -f libsupc++/libsupc++convenience.la; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ libsupc++convenience.la
rm -f libsupc++/new_handler.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ new_handler.lo
rm -f libsupc++/new_op.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ new_op.lo
rm -f libsupc++/new_opnt.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ new_opnt.lo
rm -f libsupc++/new_opv.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ new_opv.lo
rm -f libsupc++/new_opvnt.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ new_opvnt.lo
rm -f libsupc++/pure.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ pure.lo
rm -f libsupc++/tinfo.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ tinfo.lo
rm -f libsupc++/tinfo2.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ tinfo2.lo
rm -f libsupc++/vec.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ vec.lo
rm -f libsupc++/vterminate.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C libsupc++ vterminate.lo
rm -f src/allocator-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src allocator-inst.lo
rm -f src/allocator.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src allocator.lo
rm -f src/atomicity.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src atomicity.lo
rm -f src/basic_file.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src basic_file.lo
rm -f src/c++locale.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src c++locale.lo
rm -f src/codecvt.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src codecvt.lo
rm -f src/codecvt_members.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src codecvt_members.lo
rm -f src/collate_members.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src collate_members.lo
rm -f src/complex_io.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src complex_io.lo
rm -f src/concept-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src concept-inst.lo
rm -f src/ctype.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ctype.lo
rm -f src/ctype_members.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ctype_members.lo
rm -f src/debug.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src debug.lo
rm -f src/debug_list.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src debug_list.lo
rm -f src/ext-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ext-inst.lo
rm -f src/fstream-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src fstream-inst.lo
rm -f src/functexcept.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src functexcept.lo
rm -f src/globals_io.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src globals_io.lo
rm -f src/globals_locale.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src globals_locale.lo
rm -f src/io-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src io-inst.lo
rm -f src/ios.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ios.lo
rm -f src/ios_failure.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ios_failure.lo
rm -f src/ios_init.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ios_init.lo
rm -f src/ios_locale.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ios_locale.lo
rm -f src/istream-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src istream-inst.lo
rm -f src/libstdc++.la; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src libstdc++.la
rm -f src/limits.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src limits.lo
rm -f src/list.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src list.lo
rm -f src/locale-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src locale-inst.lo
rm -f src/locale-misc-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src locale-misc-inst.lo
rm -f src/locale.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src locale.lo
rm -f src/locale_facets.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src locale_facets.lo
rm -f src/locale_init.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src locale_init.lo
rm -f src/localename.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src localename.lo
rm -f src/messages_members.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src messages_members.lo
rm -f src/misc-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src misc-inst.lo
rm -f src/monetary_members.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src monetary_members.lo
rm -f src/numeric_members.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src numeric_members.lo
rm -f src/ostream-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src ostream-inst.lo
rm -f src/sstream-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src sstream-inst.lo
rm -f src/stdexcept.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src stdexcept.lo
rm -f src/streambuf-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src streambuf-inst.lo
rm -f src/string-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src string-inst.lo
rm -f src/strstream.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src strstream.lo
rm -f src/time_members.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src time_members.lo
rm -f src/tree.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src tree.lo
rm -f src/valarray-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src valarray-inst.lo
rm -f src/wlocale-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src wlocale-inst.lo
rm -f src/wstring-inst.lo; make CC='"$(MOSYNCDIR)/bin/xgcc" -MMD' CXX='"$(MOSYNCDIR)/bin/xgcc" -I"$(MOSYNCDIR)/include" -MMD' -C src wstring-inst.lo
