#!/bin/sh

#
# This script computes the various flags needed to run GNU C++ testsuites
# (compiler specific as well as library specific). 
#
# Written by Benjamin Kosnik <bkoz@redhat.com>
#            Gabriel Dos Reis <gdr@codesourcery.com>
#

# Print a message saying how this script is intended to be invoked
print_usage() {
    cat <<EOF
Usage: 
    testsuite_flags --install-includes
		    --build-includes
		    --build-cxx
		    --install-cxx
		    --cxxflags
		    --cxxpchflags
EOF
}

# Establish configure-generated directory structure.
BUILD_DIR=/home/roman/Sources/MoSync-gcc3/gcc-3.4.6/libstdc++-v3
SRC_DIR=/home/roman/Sources/MoSync-gcc3/gcc-3.4.6/libstdc++-v3
PREFIX_DIR=NONE
query=$1

case ${query} in
    --install-includes)
      INCLUDES="-I${SRC_DIR}/testsuite"
      echo ${INCLUDES}
      ;;
    --build-includes)
      INCLUDES="-nostdinc++ -I../include/mapip -I../include -I../libsupc++ -I${SRC_DIR}/libsupc++ 
                -I${SRC_DIR}/include/backward -I${SRC_DIR}/testsuite"
      echo ${INCLUDES}
      ;;
    --install-cxx)
      CXX=${PREFIX_DIR}/bin/g++
      echo ${CXX}
      ;;
    --build-cxx)
      CXX_build="/opt/MoSync-4.0-Alpha/bin/xgcc -x c++"
      CXX=`echo "$CXX_build" | sed 's,gcc/xgcc ,gcc/g++ ,'`
      echo ${CXX}
      ;;
    --cxxflags)
      CXXFLAGS_save="-g -O2 -D_GLIBCXX_ASSERT"
      CXXFLAGS_config='  -fmessage-length=0 
 		       -DLOCALEDIR="/home/roman/Sources/MoSync-gcc3/gcc-3.4.6/libstdc++-v3/po/share/locale" '
      echo ${CXXFLAGS_save} ${CXXFLAGS_config}
      ;;
    --cxxpchflags)
      PCHFLAGS="-include bits/stdc++.h"
      echo ${PCHFLAGS}
      ;;
    *)
      print_usagex
      ;;
esac

exit 0
